//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUsers
    {
        public AspNetUsers()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaims>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogins>();
            this.ProductsWatchers = new HashSet<ProductsWatchers>();
            this.UserDevices = new HashSet<UserDevices>();
            this.UserProductsConsumed = new HashSet<UserProductsConsumed>();
            this.UserProductsList = new HashSet<UserProductsList>();
            this.UserProductsListHistory = new HashSet<UserProductsListHistory>();
            this.UserProductsQueue = new HashSet<UserProductsQueue>();
            this.AspNetRoles = new HashSet<AspNetRoles>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual ICollection<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual ICollection<ProductsWatchers> ProductsWatchers { get; set; }
        public virtual ICollection<UserDevices> UserDevices { get; set; }
        public virtual ICollection<UserProductsConsumed> UserProductsConsumed { get; set; }
        public virtual ICollection<UserProductsList> UserProductsList { get; set; }
        public virtual ICollection<UserProductsListHistory> UserProductsListHistory { get; set; }
        public virtual ICollection<UserProductsQueue> UserProductsQueue { get; set; }
        public virtual ICollection<AspNetRoles> AspNetRoles { get; set; }
    }
}
