//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessProductsListHistory
    {
        public int Id { get; set; }
        public int BusinessId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<double> Price { get; set; }
        public string ListName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> LisieHome { get; set; }
        public System.DateTime InsertDate { get; set; }
    }
}
