//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpiroStockManagementEntities : DbContext
    {
        public SpiroStockManagementEntities()
            : base("name=SpiroStockManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public virtual DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public virtual DbSet<aspnet_Paths> aspnet_Paths { get; set; }
        public virtual DbSet<aspnet_PersonalizationAllUsers> aspnet_PersonalizationAllUsers { get; set; }
        public virtual DbSet<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
        public virtual DbSet<aspnet_Profile> aspnet_Profile { get; set; }
        public virtual DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public virtual DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
        public virtual DbSet<aspnet_Users> aspnet_Users { get; set; }
        public virtual DbSet<aspnet_WebEvent_Events> aspnet_WebEvent_Events { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Marketing> Marketing { get; set; }
        public virtual DbSet<ProductCategories> ProductCategories { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<StoreProducts> StoreProducts { get; set; }
        public virtual DbSet<StoreProductsTemp> StoreProductsTemp { get; set; }
        public virtual DbSet<Stores> Stores { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserProductsBuys> UserProductsBuys { get; set; }
        public virtual DbSet<UserProductsConsumed> UserProductsConsumed { get; set; }
        public virtual DbSet<UserProductsList> UserProductsList { get; set; }
        public virtual DbSet<UserProductsListHistory> UserProductsListHistory { get; set; }
        public virtual DbSet<UserProductsQueue> UserProductsQueue { get; set; }
        public virtual DbSet<UserProductsShoppingList> UserProductsShoppingList { get; set; }
        public virtual DbSet<UserProductsStockList> UserProductsStockList { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<BusinessDevices> BusinessDevices { get; set; }
        public virtual DbSet<Businesses> Businesses { get; set; }
        public virtual DbSet<BusinessLisieHome> BusinessLisieHome { get; set; }
        public virtual DbSet<BusinessProducts> BusinessProducts { get; set; }
        public virtual DbSet<BusinessProductsList> BusinessProductsList { get; set; }
        public virtual DbSet<BusinessProductsListHistory> BusinessProductsListHistory { get; set; }
        public virtual DbSet<BusinessProductsOnQueue> BusinessProductsOnQueue { get; set; }
        public virtual DbSet<BusinessProductsStockChangesHistory> BusinessProductsStockChangesHistory { get; set; }
        public virtual DbSet<IngredientProducts> IngredientProducts { get; set; }
        public virtual DbSet<Ingredients> Ingredients { get; set; }
        public virtual DbSet<Interactions> Interactions { get; set; }
        public virtual DbSet<LisieHome> LisieHome { get; set; }
        public virtual DbSet<LisieUpdaters> LisieUpdaters { get; set; }
        public virtual DbSet<Lyrics> Lyrics { get; set; }
        public virtual DbSet<ProductPricesUpdates> ProductPricesUpdates { get; set; }
        public virtual DbSet<ProductPricesUpdatesFails> ProductPricesUpdatesFails { get; set; }
        public virtual DbSet<ProductsAutoMatched> ProductsAutoMatched { get; set; }
        public virtual DbSet<ProductsBarcodeFoundAuchan> ProductsBarcodeFoundAuchan { get; set; }
        public virtual DbSet<ProductsNewStores> ProductsNewStores { get; set; }
        public virtual DbSet<ProductsReview> ProductsReview { get; set; }
        public virtual DbSet<ProductsUpdating> ProductsUpdating { get; set; }
        public virtual DbSet<ProductsWatchers> ProductsWatchers { get; set; }
        public virtual DbSet<Recepies> Recepies { get; set; }
        public virtual DbSet<RecipeDirections> RecipeDirections { get; set; }
        public virtual DbSet<RecipeIngredients> RecipeIngredients { get; set; }
        public virtual DbSet<SelfJungleMaestro_PlantStatus> SelfJungleMaestro_PlantStatus { get; set; }
        public virtual DbSet<SelfJungleMaestro_RoomStatus> SelfJungleMaestro_RoomStatus { get; set; }
        public virtual DbSet<SmokeCigaretteHistory> SmokeCigaretteHistory { get; set; }
        public virtual DbSet<Statistics> Statistics { get; set; }
        public virtual DbSet<StoreGetterLastCategory> StoreGetterLastCategory { get; set; }
        public virtual DbSet<TaskManagerTasks> TaskManagerTasks { get; set; }
        public virtual DbSet<UndeadMachinas> UndeadMachinas { get; set; }
        public virtual DbSet<UserBuyingOnlineStatus> UserBuyingOnlineStatus { get; set; }
        public virtual DbSet<UserDevices> UserDevices { get; set; }
        public virtual DbSet<UserNotes> UserNotes { get; set; }
        public virtual DbSet<UserProductsSimple> UserProductsSimple { get; set; }
        public virtual DbSet<UsersApple> UsersApple { get; set; }
        public virtual DbSet<UserSpokenProducts> UserSpokenProducts { get; set; }
        public virtual DbSet<UserTotalSavings> UserTotalSavings { get; set; }
        public virtual DbSet<UserUpdatePricesRequests> UserUpdatePricesRequests { get; set; }
    }
}
