//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsAutoMatched
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int StoreId { get; set; }
        public string MatchType { get; set; }
        public Nullable<double> ImageTogetherTextEqualsPercentage { get; set; }
        public Nullable<double> Last2Avg { get; set; }
        public Nullable<double> ImageTextEqualsPercentage { get; set; }
        public Nullable<double> ImagesTogetherPercentage { get; set; }
        public Nullable<double> TxPoTxTogetherPo { get; set; }
        public Nullable<int> SortWeight { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
