//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.ProductsWatchers = new HashSet<ProductsWatchers>();
            this.StoreProducts = new HashSet<StoreProducts>();
            this.UserProductsConsumed = new HashSet<UserProductsConsumed>();
            this.UserProductsList = new HashSet<UserProductsList>();
            this.UserProductsListHistory = new HashSet<UserProductsListHistory>();
        }
    
        public int Id { get; set; }
        public string Barcode { get; set; }
        public string Name { get; set; }
        public Nullable<double> Price { get; set; }
        public string Brand { get; set; }
        public string VariableWeightPrice { get; set; }
        public string CategoryString { get; set; }
        public string FullCategory { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string Weight { get; set; }
        public Nullable<int> AddedByUserId { get; set; }
        public string CreatedByUserId { get; set; }
        public Nullable<bool> IsTemp { get; set; }
        public Nullable<bool> CategoryCalculated { get; set; }
    
        public virtual ICollection<ProductsWatchers> ProductsWatchers { get; set; }
        public virtual ICollection<StoreProducts> StoreProducts { get; set; }
        public virtual ICollection<UserProductsConsumed> UserProductsConsumed { get; set; }
        public virtual ICollection<UserProductsList> UserProductsList { get; set; }
        public virtual ICollection<UserProductsListHistory> UserProductsListHistory { get; set; }
    }
}
