//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recepies
    {
        public Recepies()
        {
            this.RecipeDirections = new HashSet<RecipeDirections>();
            this.RecipeIngredients = new HashSet<RecipeIngredients>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Cuisine { get; set; }
        public string Category { get; set; }
        public string Yield { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<decimal> TimePreparing { get; set; }
        public Nullable<decimal> TimeCooking { get; set; }
        public Nullable<decimal> TimeReady { get; set; }
        public string Commentary { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<bool> Visible { get; set; }
    
        public virtual ICollection<RecipeDirections> RecipeDirections { get; set; }
        public virtual ICollection<RecipeIngredients> RecipeIngredients { get; set; }
    }
}
