//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeDirections
    {
        public int Id { get; set; }
        public Nullable<int> RecipeId { get; set; }
        public int StepNumber { get; set; }
        public string Direction { get; set; }
    
        public virtual Recepies Recepies { get; set; }
    }
}
