//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistics
    {
        public int Id { get; set; }
        public Nullable<int> Users { get; set; }
        public Nullable<int> UsersMonthlyActive { get; set; }
        public Nullable<int> Products { get; set; }
        public Nullable<int> Interactions { get; set; }
        public Nullable<int> ProductsAddedToConsumed { get; set; }
        public Nullable<int> ProductsAddedToShoppingList { get; set; }
        public Nullable<int> ProductsAddedToInventory { get; set; }
        public Nullable<int> ProductsAddedToBought { get; set; }
        public Nullable<int> LHBarcodesScanned { get; set; }
        public Nullable<int> LHProductsAddedToConsumed { get; set; }
        public Nullable<int> LHAddedToShoppingList { get; set; }
        public Nullable<int> LHProductsAddedToInventory { get; set; }
        public Nullable<int> LHProductsAddedToBought { get; set; }
        public System.DateTime InsertDate { get; set; }
    }
}
