//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreProducts
    {
        public int Id { get; set; }
        public int StoreId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string OnlineProductId { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> PriceRatio { get; set; }
        public string Unit { get; set; }
        public string Url { get; set; }
        public string UserId { get; set; }
        public string Barcode { get; set; }
        public string Name { get; set; }
        public string Brand { get; set; }
        public string Weight { get; set; }
        public string ImageUrl { get; set; }
        public string Category { get; set; }
        public string CategoryFull { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> NeedsUpdate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsTemp { get; set; }
        public Nullable<System.DateTime> LastSuccessfulUpdateDate { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Stores Stores { get; set; }
    }
}
