//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskManagerTasks
    {
        public int Id { get; set; }
        public string Category { get; set; }
        public string Task { get; set; }
        public Nullable<bool> Done { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
