//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UndeadMachinas
    {
        public int Id { get; set; }
        public string UndeadName { get; set; }
        public string NgrokAdress { get; set; }
        public Nullable<bool> NgrokState { get; set; }
        public string InternalIp { get; set; }
        public string ExternalIp { get; set; }
        public string Hostname { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
