//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProductsConsumed
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public string UserId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string QuantityWeight { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ActionTakenByUser { get; set; }
        public Nullable<System.DateTime> ActionTakenByUserDate { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Products Products { get; set; }
    }
}
