//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTotalSavings
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string StoreIds { get; set; }
        public int TotalProducts { get; set; }
        public double MaxPrice { get; set; }
        public double MinPrice { get; set; }
        public double PriceDifference { get; set; }
        public int Savings { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
