//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpiroStockManagement {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("teste")]
        public string OperationChoosen {
            get {
                return ((string)(this["OperationChoosen"]));
            }
            set {
                this["OperationChoosen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OperationChoosenAutomatic {
            get {
                return ((bool)(this["OperationChoosenAutomatic"]));
            }
            set {
                this["OperationChoosenAutomatic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string ChekboxAddToStock {
            get {
                return ((string)(this["ChekboxAddToStock"]));
            }
            set {
                this["ChekboxAddToStock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string ChekboxRemoveFromStock {
            get {
                return ((string)(this["ChekboxRemoveFromStock"]));
            }
            set {
                this["ChekboxRemoveFromStock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string CheckboxAddToShoopingCart {
            get {
                return ((string)(this["CheckboxAddToShoopingCart"]));
            }
            set {
                this["CheckboxAddToShoopingCart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string CheckboxRemoveFromShoopingCart {
            get {
                return ((string)(this["CheckboxRemoveFromShoopingCart"]));
            }
            set {
                this["CheckboxRemoveFromShoopingCart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BuyRecipeIngredientsAutoCompleteProductQuantity {
            get {
                return ((bool)(this["BuyRecipeIngredientsAutoCompleteProductQuantity"]));
            }
            set {
                this["BuyRecipeIngredientsAutoCompleteProductQuantity"] = value;
            }
        }
    }
}
